import {mountSceneMotion} from './sceneMotion';
import React,{useEffect,useRef,useState} from 'react';
const a=f=>'/assets/'+f;
export function App(){
 useEffect(mountSceneMotion,[]);
 const dialog=useRef(null),opener=useRef(null);const [image,setImage]=useState(null);
 const pic=(file,title,cls='')=><button className={'picture '+cls} aria-label={'放大查看：'+title} onClick={e=>{opener.current=e.currentTarget;setImage({file,title});dialog.current.showModal()}}><img src={a(file)} alt={title} loading="lazy"/><span className="caption">{title}<small>放大查看</small></span></button>;
 const person=(file,alt)=><div className="portrait"><img src={a(file)} alt={alt}/></div>;
 const chapter=(num,title)=><p className="chapter"><span>{num}</span>{title}</p>;
 const close=()=>{dialog.current.close();opener.current?.focus()};
 return <><main>
 <section className="scene intro"><div className="grid"><div className="left"><p className="eyebrow">蔡昕益 · 个人作品集</p><h1>我，<br/>不只一面<span>。</span></h1><div className="rule"/></div>{person('person-front-cutout.png','正面站立的Q版蔡昕益')}<div className="right identity"><p className="eyebrow">ABOUT ME</p><h2>蔡昕益</h2><p>广州大学</p><hr/><p className="role">创意产品 / 产品策划</p><p className="qualities">产品理解<br/>创意表达<br/>落地执行</p></div></div><a className="scroll" href="#insight">向下，看看我的另一面 <span aria-hidden="true">↓</span></a></section>
 <section className="scene insight" id="insight"><div className="grid"><div className="left">{chapter('02','左面 · 看见用户')}<h2>先看见用户的问题，<br/>再找到产品的价值。</h2><p className="lead">通过需求材料、项目方案与竞品信息，理解企业的实际关注点，把技术能力翻译成业务价值。</p><div className="relations">{[['数据敏感','明确本地处理与外部调用的边界'],['部署复杂','梳理一体化环境与预置模型的价值'],['接口分散','用统一 API 简化多模型接入'],['用量难管','通过权限、配额和监控支撑管理']].map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></div>{person('person-insight-cutout.png','手持记录板、观察产品问题的Q版人物')}<div className="right"><p className="eyebrow">AISTACK / 产品与方案</p>{pic('aistack-architecture.png','AISTACK 方案架构')}<article><small>竞品分析</small><h3>找到比较依据</h3><p>整理《API平台竞品分析》，为理解产品差异与能力表达提供参考。</p></article><article><small>方案表达</small><h3>从资料到方案</h3><p>参与企业 AI 资源统一管理解决方案、公司 AI 业务介绍与投标应答材料的整理和输出。</p></article><p className="note">图为产品方案资料，展示参与的内容工作，不代表本人开发平台。</p><p className="skills">需求理解 / 价值提炼 / 方案表达</p></div></div></section>
 <section className="scene story"><div className="grid"><div className="left">{chapter('03','右面 · 让产品成为故事')}<h2>让人愿意看下去，<br/>再让产品被理解。</h2><p className="lead">用“重生文学”建立观看动力，让产品能力成为推动故事的解决方案。</p><article><h3>AISTACK API 平台宣传视频</h3><p>独立制作 API 平台部分宣传展示视频，将故事设定与真实产品界面组织成连续的观看过程。</p></article><ol className="steps">{[['找入口','用熟悉的故事设定引起兴趣'],['串功能','将界面放进解决问题的过程'],['做成片','连接叙事与产品演示']].map(([t,p])=><li key={t}><b>{t}</b><span>{p}</span></li>)}</ol><p className="skills">叙事设计 / 视频制作 / 平台表达</p></div>{person('person-story-cutout.png','手持场记板、向外讲述的Q版人物')}<div className="right"><p className="eyebrow">FEATURED WORK / 创意视频</p><div className="story-frames">{pic('story-problem.jpg','01 / 故事起点：调用成本困扰')}{pic('story-solution.jpg','02 / 产品进入故事：统一调用入口')}{pic('story-interface.jpg','03 / 真实界面：API 密钥管理')}</div><div className="example">{pic('spark.jpg','Spark 内容样例','small')}<article><small>知君竹传媒</small><h3>不同平台，不同表达</h3><p>围绕 Spark 音箱、搜索词与艺人内容，持续生产图文并复盘。</p><dl className="spark-metrics"><div><dt>图文产出</dt><dd>200+</dd></div><div><dt>词条进榜率</dt><dd>31.11%</dd></div><div><dt>内容活动率</dt><dd>37.12%</dd></div></dl><p className="note">数据来源：原作品集记录，沿用原指标名称。</p></article></div><article className="news-results"><small>广东广播电视台</small><h3>新闻短视频传播表现</h3><p>根据突发新闻事件，独立完成短视频创作。</p><dl className="news-metrics"><div><dt>单条播放</dt><dd>7495万+</dd></div><div><dt>点赞</dt><dd>13.9万+</dd></div><div><dt>分享</dt><dd>44.3万+</dd></div></dl><p className="note">数据来源：原作品集中的历史记录。</p><details><summary>查看作品与数据截图</summary>{pic('news-evidence.jpg','原作品集中的新闻作品记录')}</details></article><p className="note">内容产出数据依据原作品集记录。</p></div></div></section>
 <section className="scene learn"><div className="grid"><div className="left">{chapter('04','上面 · 向上探索')}<h2>从真实任务出发，<br/>建立自己的学习路径。</h2><p className="lead">面对信息分散、重复整理与长文档阅读，先拆解任务，再选择工具，把实践沉淀成方法。</p><ol className="path">{[['看清任务','哪些步骤重复，哪些判断需要人完成。'],['拆解流程','明确输入、处理规则与输出格式。'],['选择工具','按任务使用 n8n、Coze 和大模型。'],['回到证据','核对结果，记录限制，沉淀可复用流程。']].map(([t,p],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{p}</p></div></li>)}</ol></div>{person('person-learn-cutout.png','向上观察学习节点的Q版人物')}<div className="right"><p className="eyebrow">LEARNING BY DOING / 实践</p>{pic('n8n.jpg','n8n 多源资讯工作流')}<article><h3>把分散信息组织起来</h3><p>多源采集 → AI 清洗分类 → 结构化归档至飞书多维表格。</p></article><article className="skill-case"><small>Tender Intelligence Engine</small><h3>让分析有据可查</h3><p>将招标预读组织为事实提取、证据定位、风险梳理与交付检查。</p><p className="tags">文件事实 / 分析判断 / 信息缺口</p>{pic('tender-report.png','招标分析报告 · 决策摘要（原报告第1页）','report-preview')}<p className="note">规则要求关键结论标注文件与页码、章节或关键词。</p></article><p className="note">其他实践：Coze 内容分析与生成、AI 辅助产品资料整理。</p><p className="skills">任务拆解 / AI 应用 / 方法沉淀</p></div></div></section>
 <section className="scene grow"><div className="grid"><div className="left">{chapter('05','下面 · 不断补足自己')}<h2>看见能力的缺口，<br/>用项目一步步补齐。</h2><p className="lead">创意表达是我的起点。我也在通过实际项目，补足数据判断、商业思考与协作执行。</p><article><small>补数据判断</small><h3>Retailrocket 用户行为分析</h3><p>通过 SQL 与 AI 辅助分析，梳理热门商品、行为漏斗与用户分层，把发现转化为运营建议。</p></article><article><small>补商业思考</small><h3>Mate80 课程营销策划</h3><p>分析目标人群与竞品定位，设计预热、发布、续热三阶段节奏。</p><p className="note">课程模拟项目；预算与指标均为方案预设。</p></article>{pic('marketing-plan.jpg','Mate80 三阶段传播节奏 · 课程模拟')}</div>{person('person-grow-cutout.png','俯看能力拼图的Q版人物')}<div className="right"><p className="eyebrow">MAKE IT HAPPEN / 协作与执行</p>{pic('opc.jpg','AISTACK OPC 展会现场','opc')}<article><small>补协作执行</small><h3>让产出进入真实项目</h3><p>参与 AISTACK 方案材料梳理与交付、OPC 线下展会策划；配合渠道经理推进 Spark 内容投放。</p></article><div className="project-evidence"><h3>数据分析与营销策划</h3><div className="evidence-grid">{pic('retail.png','商品浏览分析 · 历史过程图')}{pic('marketing-audience.jpg','目标人群与竞品定位 · 课程模拟')}</div><p className="note">数据分析图保留历史记录；营销策划为课程模拟项目。</p></div><p className="skills">数据意识 / 商业思考 / 协作执行</p></div></div></section>
 <section className="scene closing"><div className="grid"><div className="left"><h2>不只一面<span>。</span></h2><p className="ending">希望下一次见面，<br/>不只是面试。</p></div>{person('person-real-cutout.png','蔡昕益向镜头伸手的形象图')}<div className="right contact"><p>蔡昕益</p><p>2763841742@qq.com</p></div></div></section>
 </main><dialog ref={dialog} className="lightbox" onClick={e=>{if(e.target===e.currentTarget)close()}} onCancel={()=>opener.current?.focus()}><div className="modal-header"><p>{image?.title}</p><button onClick={close} autoFocus>关闭</button></div>{image&&<img src={a(image.file)} alt={image.title}/>}</dialog></>;
}
